"""create all tables

Revision ID: 53ad0731f444
Revises: 7fcdb7c5abbc
Create Date: 2025-08-02 13:53:05.915410

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '53ad0731f444'
down_revision = '7fcdb7c5abbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
