"""recreate schema

Revision ID: 7fcdb7c5abbc
Revises: 04d8dad75204
Create Date: 2025-08-02 13:51:43.870479

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7fcdb7c5abbc'
down_revision = '04d8dad75204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
